/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webserver;

public class App {
    public static void main(String[] args) {
        SocketHandler socketHandler = new SocketHandler(8080, 10);
        socketHandler.startServer();
    }
}
