/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webserver;

import java.net.Socket;

public class App {
    public static void main(String[] args) {
        //String cwd = System.getProperty("user.dir");
        //System.out.println(cwd);
        SocketHandler socketHandler = new SocketHandler(8080, 10);
        socketHandler.startServer();
    }
}
